# -*- mode: org; coding: utf-8; fill-column: 79 -*-
#+TITLE: My emacs configuration file
#+AUTHOR: Sébastien Brisard
#+CATEGORY: DOTEMACS
#+PROPERTY: header-args:emacs-lisp :tangle yes :results output silent

#+BEGIN_SRC emacs-lisp
  ;; Vanilla emacs configuration
  ;; ===========================
  ;;
  (setq column-number-mode t
	confirm-nonexistent-file-or-buffer t
	delete-active-region nil
	dnd-open-file-other-window nil
	find-file-run-dired nil
	indent-tabs-mode nil
	inhibit-startup-screen t
	initial-frame-alist '((top . 0) (left . 0))
	make-backup-files nil
	ps-paper-type (quote a4)
	safe-local-variable-values (quote ((buffer-auto-save-file-name)
					   (org-confirm-babel-evaluate)))
	show-paren-style (quote expression)
	visible-bell t)
  ;;(setq-default buffer-file-coding-system 'utf-8)

  (global-auto-revert-mode)
  (global-hl-line-mode)
  (menu-bar-mode -1)
  (scroll-bar-mode -1)
  (show-paren-mode)
  (tool-bar-mode -1)

  (global-unset-key (kbd "<C-next>"))
  (global-unset-key (kbd "<C-prior>"))


  ;; Definition of my own customization group
  ;; ----------------------------------------
  ;;
  (defgroup sb nil
    "My customization group.

  Gathers platform-dependent custom variables (both built-in and
  user-defined) that are required by my setup. These custom variables
  should be set at each new fresh install (but sensible defaults are
  defined)."
    :tag "sb")

  (defcustom sb-path-to-local-documents "~/Documents"
    "Path to the documents directory.

  It is in particular assumed that

    - my org notes are located in the notes/ subdirectory,
    - my blog files are located in the blog/ subdirectory.

  Under Linux, this variable might be set to

      /home/username/Documents

  while under Windows, it might be set to

      C:\\Users\\username\\Documents

  In most cases, the default value

      ~/Documents

  should work."
    :type 'string :group 'sb :tag "Path to local documents")

  (defcustom sb-path-to-bibliography "~/MyCoRe/biblio"
    "Path to the local bibliography.

  See `sb-insert-bibref' for more details."
    :type 'string :group 'sb :tag "Path to bibliography")

  ;; Remember to configure path to Julia program if necessary
  (custom-add-to-group 'sb 'julia-program 'custom-variable)

  ; Remember to configure proxy if necessary
  (custom-add-to-group 'sb 'url-proxy-services 'custom-variable)

  (custom-add-to-group 'sb 'python-shell-interpreter-args 'custom-variable)
  (custom-add-to-group 'sb 'python-shell-interpreter-interactive-arg 'custom-variable)
#+END_SRC

#+BEGIN_SRC emacs-lisp
  ; This is required for M-x package-list-packages to work properly
  (prefer-coding-system 'utf-8)

  (require 'package)
  (setq package-archives
        '(("gnu" . "http://elpa.gnu.org/packages/")
          ("melpa" . "http://melpa.org/packages/")
          ("melpa-stable" . "http://stable.melpa.org/packages/")
          ("elpy" . "http://jorgenschaefer.github.io/packages/")
          ;("org" . "https://orgmode.org/elpa/")
          ))
  (package-initialize)

  (defun sb-package-install-unless-installed (pkg)
    (unless (package-installed-p pkg) (package-install pkg)))
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (sb-package-install-unless-installed 'spacemacs-theme)
  (setq spacemacs-theme-org-height nil)
  (load-theme 'spacemacs-dark)

  (set-face-font 'default "DejaVu Sans Mono")
#+END_SRC

#+BEGIN_SRC emacs-lisp
  ; input-method conflicts with key-chord, which I do not use
  (setq default-input-method 'rfc1345)
  (defun sb-activate-input-method ()
    (activate-input-method default-input-method))
  (add-hook 'text-mode-hook 'sb-activate-input-method)
  (add-hook 'org-mode-hook 'sb-activate-input-method)
#+END_SRC

* Functions and variables to be used in this file
  :LOGBOOK:
  CLOCK: [2016-09-15 Thu 07:28]--[2016-09-15 Thu 07:46] =>  0:18
  CLOCK: [2016-09-05 Mon 08:15]--[2016-09-05 Mon 08:30] =>  0:15
  CLOCK: [2016-08-23 Tue 07:45]--[2016-08-23 Tue 07:50] =>  0:05
  :END:

** Dedicated custom group

The custom group SB gathers some variables which must be set locally.


** Load a file only when it exists

#+BEGIN_SRC emacs-lisp
  (defun sb-load-file-when-exists (filename)
    "Load specified file if it exists. Do nothing otherwise."
    (when (file-exists-p filename) (load-file filename)))
#+END_SRC

** Toggle window dedication

See [[http://stackoverflow.com/questions/5151620/how-do-i-make-this-emacs-frame-keep-its-buffer-and-not-get-resized][stack overflow]]

#+BEGIN_SRC emacs-lisp
  (defun sb-toggle-window-dedicated ()
    "Toggle whether the current active window is dedicated or not."
    (interactive)
    (message
     (if (let (window (get-buffer-window (current-buffer)))
           (set-window-dedicated-p window
                                   (not (window-dedicated-p window))))
         "Window '%s' is dedicated"
       "Window '%s' is normal")
     (current-buffer)))
#+END_SRC

** Bind newline and indent to RET

In programming mode, it can be inconvenient to use =C-j= to call =newline-and-indent=. The following function is not necessary with Python (when using elpy-mode).

#+BEGIN_SRC emacs-lisp
  (defun sb-bind-newline-and-indent-to-RET ()
    "Bind newline-and-indent to RET.

  This function can be used as a hook."
    (local-set-key (kbd "RET") 'newline-and-indent))
#+END_SRC

* Platform dependent settings

** Predicates
   :LOGBOOK:
   CLOCK: [2016-09-15 Thu 07:22]--[2016-09-15 Thu 07:25] =>  0:03
   :END:

These predicates allow to assert the platform on which emacs currently runs.

#+BEGIN_SRC emacs-lisp
  (defvar windowsp (string-equal "windows-nt" (symbol-name system-type)))
  (defvar darwinp (string-equal "darwin" (symbol-name system-type)))
  (defvar linuxp (string-equal "gnu/linux" (symbol-name system-type)))
#+END_SRC

** Linux settings

** Mac OS X settings

Under Mac OS X, right-alt must be mapped to Alt Gr.

#+BEGIN_SRC emacs-lisp
  (when darwinp
    (setq mac-option-modifier 'none)
    (setq mac-command-modifier 'meta))
#+END_SRC

** Windows settings

* My personal keymap
:LOGBOOK:
CLOCK: [2017-02-01 Wed 05:25]--[2017-02-01 Wed 05:45] =>  0:20
CLOCK: [2017-01-31 Tue 07:30]--[2017-01-31 Tue 08:00] =>  0:30
CLOCK: [2017-01-31 Tue 05:15]--[2017-01-31 Tue 05:40] =>  0:25
:END:

Ben Maughan at Pragmatic Emacs has an [[http://pragmaticemacs.com/emacs/use-your-digits-and-a-personal-key-map-for-super-shortcuts/][interesting post]] on unbinding =C-1=, ..., =C-9= and =M-1=, ..., =M-9=, which he rarely uses. In turn, these can be used as prefix keys. This is not so interesting for french keyboards, since typing digits actually requires holding the =shift= key.

See also the [[https://www.emacswiki.org/emacs/PrefixKey][EmacsWiki]] on prefix keys.

My personal keymap is called =sb-map=, and the prefix key that is assigned to this keymap is =C-&=.

#+BEGIN_SRC emacs-lisp
  (define-prefix-command 'sb-map)
  (global-set-key (kbd "C-&") 'sb-map)
#+END_SRC

* Various packages
:LOGBOOK:
CLOCK: [2016-10-20 Thu 21:15]--[2016-10-20 Thu 21:55] =>  0:40
:END:

** Others

=htmlize= is used by [[#ORG_MODE][Org mode]] for fontification of code blocks.

#+BEGIN_SRC emacs-lisp
  (require 'htmlize)
#+END_SRC

* Navigation

Some interesting references

  - [[http://irreal.org/blog/?p%3D5309][Defining a Keymap Prefix (Ireal)]]
  - See function move-to-window-line-top-bottom, bound to =M-r=

** Default directory
   :LOGBOOK:
   CLOCK: [2016-08-17 Wed 08:30]--[2016-08-17 Wed 08:40] =>  0:10
   :END:

Default directory is retrieved programmatically from the environment variable =HOME=

#+BEGIN_SRC emacs-lisp
  (setq default-directory (concat (getenv "HOME") "/"))
#+END_SRC

** Zap to char vs. zap up to char
   :LOGBOOK:
   CLOCK: [2016-06-15 Wed 08:00]--[2016-06-15 Wed 08:15] =>  0:15
   :END:

=zap-to-char= (bound to =M-z=) kills up to and including the specified char. =misc.el= provides an alternative function, namely =zap-up-to-char= which does not remove the specified char. However, =misc.el= is not loaded by default.

#+BEGIN_SRC emacs-lisp
  (autoload 'zap-up-to-char "misc"
    "Kill up to, but not including ARGth occurrence of CHAR.")
  (global-set-key (kbd "M-z") 'zap-up-to-char)
#+END_SRC

** ibuffer
:LOGBOOK:
CLOCK: [2016-10-22 Sat 06:50]--[2016-10-22 Sat 07:05] =>  0:15
CLOCK: [2016-09-29 Thu 08:10]--[2016-09-29 Thu 08:45] =>  0:35
CLOCK: [2016-08-19 Fri 07:35]--[2016-08-19 Fri 07:40] =>  0:05
:END:

From the [[https://www.emacswiki.org/emacs/IbufferMode][EmacsWiki]]

#+BEGIN_QUOTE
Ibuffer is an advanced replacement for BufferMenu, which lets you operate on buffers much in the same manner as Dired. The most important Ibuffer features are highlighting and various alternate layouts. Ibuffer is part of Emacs 22.
#+END_QUOTE

See also

  - [[https://mytechrants.wordpress.com/2010/03/25/emacs-tip-of-the-day-start-using-ibuffer-asap/][Emacs Tip of the Day: Start Using IBuffer ASAP]]
  - [[http://martinowen.net/blog/2010/02/03/tips-for-emacs-ibuffer.html][Tips for using Emacs Ibuffer]]
  - [[http://www.emacswiki.org/emacs/IbufferMode][IBuffer mode]]

#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-x C-b") 'ibuffer)
  (setq ibuffer-default-sorting-mode (quote filename/process))
#+END_SRC

Let us create a few groups and not show empty filter groups

#+BEGIN_SRC emacs-lisp
  (setq ibuffer-show-empty-filter-groups nil)
  (setq ibuffer-saved-filter-groups
        (quote
         (("sb-ibuffer-groups"
           ("Notes professionnelles" (filename . "notes/professionnelles"))
           ("Notes personnelles" (filename . "notes/personnelles"))
           ("HDR" (filename . "HDR"))
           (".emacs" (filename . ".emacs.d"))))))
#+END_SRC

Then, load these groups at startup

#+BEGIN_SRC emacs-lisp
  (add-hook 'ibuffer-mode-hook
            (lambda () (ibuffer-switch-to-saved-filter-groups "sb-ibuffer-groups")))
#+END_SRC

Do not show empty groups

** Cycle spacing
:LOGBOOK:
CLOCK: [2017-03-08 Wed 08:30]--[2017-03-08 Wed 08:45] =>  0:15
:END:

The idea from this configuration comes from Ben Maughan at [[http://pragmaticemacs.com/emacs/cycle-spacing/][Pragmatic Emacs]].

=M-SPC= is bound to [[elisp:(describe-function%20'just-one-space)][just-one-space]], but [[elisp:(describe-function 'cycle-spacing)][cycle-spacing]] is more interesting, since (when called multiple times), it cycles between the following states

  1. leave just one space,
  2. delete all spaces,
  3. restore the original whitespace and point.

This function is therefore bound to =M-SPC=.

#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "M-SPC") 'cycle-spacing)
#+END_SRC

* Appearance

** Theme
   :LOGBOOK:
   CLOCK: [2016-08-23 Tue 07:50]--[2016-08-23 Tue 08:00] =>  0:10
   :END:

I use the [[https://github.com/bbatsov/zenburn-emacs][Zenburn theme]] when emacs is run in GUI mode.

#+BEGIN_SRC emacs-lisp
;;  (when (display-graphic-p) (load-theme 'zenburn t))
#+END_SRC

** A_FAIRE Frame size
   :LOGBOOK:
   CLOCK: [2016-09-15 Thu 07:26]--[2016-09-15 Thu 07:27] =>  0:01
   CLOCK: [2016-08-23 Tue 08:00]--[2016-08-23 Tue 08:10] =>  0:10
   :END:

The function [[elisp:(describe-function 'frame-monitor-attributes)][frame-monitor-attributes]] might be helpful to conditionally resize the main frame. See also [[http://stackoverflow.com/questions/16481984/get-width-of-current-monitor-in-emacs-lisp][Get width of current monitor in Emacs Lisp]].

#+BEGIN_SRC emacs-lisp
  (when window-system
    (split-window-right))
#+END_SRC

** Fonts
:LOGBOOK:
CLOCK: [2016-12-01 Thu 07:20]--[2016-12-01 Thu 08:00] =>  0:40
:END:

  - [[http://dev.carrois.com/fira-3-1/][Fira Mono]]
  - [[http://larsenwork.com/monoid/][Monoid]]
  - [[http://www.google.com/get/noto/#/][Google Noto Fonts]]
  - [[http://input.fontbureau.com/][Input]] is a flexible system of fonts designed specifically for code by David Jonathan Ross. It offers both monospaced and proportional fonts, all with a large range of widths, weights, and styles for richer code formatting.
  - [[http://sourcefoundry.org/hack/][Hack]] : police pour la programmation
  - [[https://www.google.com/fonts/specimen/Cousine][Cousine]] was designed by Steve Matteson as an innovative, refreshing sans serif design that is metrically compatible with Courier New™. Cousine offers improved on-screen readability characteristics and the pan-European WGL character set and solves the needs of developers looking for width-compatible fonts to address document portability across platforms.
  - [[https://github.com/adobe-fonts/source-code-pro][Source Code Pro]] is a set of OpenType fonts that have been designed to work well in user interface (UI) environments. In addition to a functional OpenType font, this open source project provides all of the source files that were used to build this OpenType font by using the AFDKO makeotf tool.
  - [[https://github.com/be5invis/Iosevka][Iosevka]]: spatial efficient monospace font family for programming. Built from code.

To select the font under windows, run the following command

#+BEGIN_SRC emacs-lisp :tangle no
  (w32-select-font)
#+END_SRC

Then select the desired font in the dialog that shows up. Copy the string that is returned, and insert it in your init file

#+BEGIN_SRC emacs-lisp :tangle no
  (set-face-font 'default "fontname")
#+END_SRC

* Org Mode
:PROPERTIES:
:CUSTOM_ID: ORG_MODE
:END:
:LOGBOOK:
CLOCK: [2016-11-17 Thu 08:00]--[2016-11-17 Thu 08:10] =>  0:10
CLOCK: [2016-09-22 Thu 13:10]--[2016-09-22 Thu 13:30] =>  0:20
CLOCK: [2016-09-22 Thu 12:00]--[2016-09-22 Thu 13:00] =>  1:00
CLOCK: [2016-08-30 Tue 08:10]--[2016-08-30 Tue 08:30] =>  0:20
CLOCK: [2016-08-30 Tue 07:40]--[2016-08-30 Tue 08:05] =>  0:25
CLOCK: [2016-08-29 Mon 07:30]--[2016-08-29 Mon 08:20] =>  0:50
CLOCK: [2016-08-26 Fri 08:25]--[2016-08-26 Fri 08:50] =>  0:25
CLOCK: [2016-08-25 Thu 08:35]--[2016-08-25 Thu 08:50] =>  0:15
:END:

There we are! That's really the crux of this file! Configuring Org Mode is very complex. The various configurations are organized like the [[info:Org][Org Mode Manual]].

Other resources

  - Rainer König's [[https://www.youtube.com/playlist?list=PLVtKhBrRV_ZkPnBtt_TD1Cs9PJlU0IIdE][OrgMode tutorial]]

** Introduction

*** Activation

Make agenda accessible from everywhere.

#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-c a") 'org-agenda)
#+END_SRC

** Document structure

*** Visibility cycling

**** Initial visibility

Org files are opened in folded mode.

#+BEGIN_SRC emacs-lisp
  (setq org-startup-folded t)
#+END_SRC

Wrap lines.

#+BEGIN_SRC emacs-lisp
  (setq org-startup-truncated nil)
#+END_SRC

*** Structure editing

Do not shift text to the left or right when promoting/demoting headlines.

#+BEGIN_SRC emacs-lisp
  (setq org-adapt-indentation nil)
#+END_SRC

** Tables

*** The built-in table editor

#+BEGIN_SRC emacs-lisp
  (setq org-table-copy-increment nil)
#+END_SRC

** Hyperlinks

*** Handling links]

Follow links in same window.

#+BEGIN_SRC emacs-lisp
  (setq org-link-frame-setup (quote ((vm . vm-visit-folder-other-frame)
                                     (vm-imap . vm-visit-imap-folder-other-frame)
                                     (gnus . org-gnus-no-new-news)
                                     (file . find-file-other-window)
                                     (wl . wl-other-frame))))
#+END_SRC

** TODO Items

*** Extended use of TODO keywords

**** TODO keywords as types

#+BEGIN_SRC emacs-lisp
    (setq org-todo-keywords '((sequence "A_FAIRE(a)" "EN_ATTENTE(e)" "UN_JOUR(u)"
                                        "|" "FAIT(f)")))
#+END_SRC

*** Progress logging

**** Tracking TODO state changes

#+BEGIN_SRC emacs-lisp
  (setq org-log-into-drawer t)
#+END_SRC

** Dates and times

Make sure that timestamps appear in English.

#+BEGIN_SRC emacs-lisp
  (setq system-time-locale "C")
#+END_SRC

*** Clocking work time

**** The clock table

Time durations greater than 24h should not be converted in days.

#+BEGIN_SRC emacs-lisp
  (setq org-time-clocksum-format "%02d:%02d")
#+END_SRC

Remove ugly =\_= from the clock table.

#+BEGIN_SRC emacs-lisp
  (eval-after-load "org-clock"
    '(defun org-clocktable-indent-string (level)
       "Return indentation string according to LEVEL.
  LEVEL is an integer.  Indent by two spaces per level above 1."
       (if (= level 1) ""
         (concat "→" (make-string (* 2 (- level 1)) 32)))))
#+END_SRC

#+RESULTS:
: org-clocktable-indent-string

** Agenda views

Restore window configuration upon exiting agenda. Show agenda in the current window, keeping all other windows.

#+BEGIN_SRC emacs-lisp
  (setq org-agenda-restore-windows-after-quit t)
  (setq org-agenda-window-setup 'current-window)
#+END_SRC

*** Agenda files

=*.org= and =*.txt= files are considered as agenda files. These files are looked for in

  - =~/.emacs.d= (this file!)
  - =sb-path-to-local-documents/notes= and its subdirectories (=archives= is excluded).

#+BEGIN_SRC emacs-lisp
  (setq org-agenda-file-regexp "\\`[^.].*\\.\\(org\\|txt\\)\\'")
  (setq org-agenda-files
        (let ((root (expand-file-name "notes" sb-path-to-local-documents)))
          (append (list root user-emacs-directory)
                  (remove-if (lambda (name) (or (not (file-directory-p name))
                                                (string-suffix-p ".git" name)))
                             (directory-files root t directory-files-no-dot-files-regexp)))))
#+END_SRC

** Exporting

See also

  - [[https://github.com/marsmining/ox-twbs][ox-twbs]]: export org-mode docs as HTML compatible with Twitter Bootstrap.
  - [[https://github.com/fniessen/org-html-themes][org-html-themes]]

#+BEGIN_SRC emacs-lisp
  (setq org-html-htmlize-output-type 'css)
#+END_SRC

*** Export settings

#+BEGIN_SRC emacs-lisp
  (setq org-export-preserve-breaks nil)
  (setq org-export-time-stamp-file t)
  (setq org-export-with-archived-trees 'headline)
  (setq org-export-with-author t)
  (setq org-export-with-clocks nil)
  (setq org-export-with-creator 'comment)
  (setq org-export-with-date t)
  (setq org-export-with-drawers '(not "LOGBOOK"))
  (setq org-export-with-email nil)
  (setq org-export-with-emphasize t)
  (setq org-export-with-entities t)
  (setq org-export-with-fixed-width t)
  (setq org-export-with-footnotes t)
  (setq org-export-with-inlinetasks t)
  (setq org-export-with-planning nil)
  (setq org-export-with-priority nil)
  (setq org-export-with-section-numbers nil)
  (setq org-export-with-smart-quotes nil)
  (setq org-export-with-special-strings t)
  (setq org-export-with-statistics-cookies t)
  (setq org-export-with-sub-superscripts t)
  (setq org-export-with-tables t)
  (setq org-export-with-tags t)
  (setq org-export-with-tasks t)
  (setq org-export-with-timestamps t)
  (setq org-export-with-toc nil)
  (setq org-export-with-todo-keywords t)
#+END_SRC

** Working with source code

*** Editing source code

#+BEGIN_SRC emacs-lisp
  (setq org-src-fontify-natively t)
  (setq org-src-window-setup 'other-window)
#+END_SRC

*** Evaluating code blocks

Displayed inlined images are automatically updated after evaluating source blocks. This was suggested by [[https://github.com/gregsexton/ob-ipython][ob-ipython]].

#+BEGIN_SRC emacs-lisp
  (add-hook 'org-babel-after-execute-hook 'org-display-inline-images 'append)
#+END_SRC

*** Languages

Enable languages for evaluation in source blocks.

#+BEGIN_SRC emacs-lisp
  (org-babel-do-load-languages 'org-babel-load-languages '((C . t)
                                                           (python . t)
                                                           (maxima . t)
                                                           (ipython . t)))
#+END_SRC

** Miscellaneous

*** Code evaluation and security issues

This is potentially risky!

#+BEGIN_SRC emacs-lisp
  (setq org-confirm-babel-evaluate nil)
#+END_SRC

** Formatting of times
:LOGBOOK:
CLOCK: [2017-12-11 Mon 08:00]--[2017-12-11 Mon 08:15] =>  0:15
:END:

By default, total times are printed in days, hours and minutes in clock-tables. This can be changed as follows

#+BEGIN_SRC emacs-lisp
  (setq org-duration-format (quote ((special . h:mm))))
#+END_SRC

** Hacking

*** Dynamic blocks
:LOGBOOK:
CLOCK: [2016-10-21 Fri 06:15]--[2016-10-21 Fri 06:20] =>  0:05
CLOCK: [2016-10-21 Fri 05:50]--[2016-10-21 Fri 06:05] =>  0:15
CLOCK: [2016-10-18 Tue 08:40]--[2016-10-18 Tue 09:20] =>  0:40
CLOCK: [2016-10-17 Mon 08:55]--[2016-10-17 Mon 09:05] =>  0:10
CLOCK: [2016-10-13 Thu 08:15]--[2016-10-13 Thu 08:25] =>  0:10
:END:

I intended to develop a dynamic block that would automatically insert (and update) a table of contents at the top of the current org buffer. However, I realized that [[info:Org#Visibility%20cycling][visibility cycling]] (a feature I did not use much previously) was exactly what I was looking for. So I gave up this project entirely. However, what I learned in the process was interesting. Here is a small code snippet that returns a list of the titles of all headlines in the current buffer (see the [[http://orgmode.org/worg/dev/org-element-api.html][Org Element API]]).

#+BEGIN_SRC emacs-lisp :tangle no :results value replace
  (let ((tree (org-element-parse-buffer 'headline)))
    (org-element-map tree 'headline
      (lambda (hl)
        (org-element-property :raw-value hl))))
#+END_SRC

** ob-ipython
:LOGBOOK:
CLOCK: [2017-02-11 Sat 05:30]--[2017-02-11 Sat 06:35] =>  1:05
CLOCK: [2016-08-31 Wed 05:50]--[2016-08-31 Wed 06:05] =>  0:15
CLOCK: [2015-12-01 Tue 08:20]--[2015-12-01 Tue 08:45] =>  0:25
CLOCK: [2015-11-24 Tue 07:45]--[2015-11-24 Tue 09:00] =>  1:15
CLOCK: [2015-11-05 Thu 07:15]--[2015-11-05 Thu 08:15] =>  1:00
CLOCK: [2015-11-03 Tue 08:00]--[2015-11-03 Tue 08:30] =>  0:30
:END:

[[https://github.com/gregsexton/ob-ipython][ob-ipython]] provides org-babel integration with Jupyter for evaluation of (Python by default) code blocks.

The following commands invoke ob-ipython with a specific profile.

#+BEGIN_SRC emacs-lisp
  (require 'ob-ipython)
  ;(setq ob-ipython-kernel-extra-args (quote ("--profile=ob-ipython")))
#+END_SRC

For the anaconda distribution, the package =jupyter_console= must be installed. The =ob-ipython= Jupyter profile was created as follows

#+BEGIN_EXAMPLE
ipython profile create ob-ipython
#+END_EXAMPLE

The config file is then located in =~/.ipython/profile_ob-ipython/ipython_config.py=. Its contents is reproduced below.

#+BEGIN_SRC python
  c.InteractiveShellApp.exec_lines = [
      'import matplotlib.pyplot as plt',
      'import numpy as np',
      'plt.style.use("zenburn")',
  ]

  c.InteractiveShellApp.matplotlib = 'inline'
  c.TerminalIPythonApp.display_banner = False
#+END_SRC

Note: the above apparently no longer works with Jupyter 4.0 (see [[jupyter.readthedocs.io/en/latest/projects/config.html][Jupyter’s Common Configuration Approach]]). I give up alltogether this configuration.

A zenburn stylesheet was also created for Matplotlib. File =~/.matplotlib/stylelib/zenburn.mplstyle= is reproduced below

#+BEGIN_EXAMPLE
text.color : dcdccc
axes.facecolor : 3f3f3f
axes.edgecolor : dcdccc
axes.labelcolor : dcdccc
axes.prop_cycle : cycler('color', ['8cd0d3', '7f9f7f', 'cc9393', '93e0e3', 'dc8cc3', 'f0dfaf', 'dcdccc'])
xtick.color : dcdccc
ytick.color : dcdccc
figure.facecolor : 3f3f3f
savefig.facecolor : 3f3f3f
#+END_EXAMPLE

* Magit
:LOGBOOK:
CLOCK: [2016-09-24 Sat 06:25]--[2016-09-24 Sat 06:30] =>  0:05
CLOCK: [2016-09-24 Sat 05:55]--[2016-09-24 Sat 06:20] =>  0:25
CLOCK: [2016-09-23 Fri 08:25]--[2016-09-23 Fri 08:55] =>  0:30
CLOCK: [2016-09-15 Thu 08:08]--[2016-09-15 Thu 08:25] =>  0:17
CLOCK: [2016-04-21 Thu 07:25]--[2016-04-21 Thu 08:25] =>  1:00
:END:

From the [[https://magit.vc/about/][official website]]

#+BEGIN_QUOTE
Magit is an interface to the version control system [[https://git-scm.com/][Git]], implemented as an [[https://www.gnu.org/software/emacs][Emacs]] package. Magit aspires to be a complete Git porcelain. While we cannot (yet) claim that Magit wraps and improves upon each and every Git command, it is complete enough to allow even experienced Git users to perform almost all of their daily version control tasks directly from within Emacs. While many fine Git clients exist, only Magit and Git itself deserve to be called porcelains.
#+END_QUOTE

This interesting video, [[https://www.youtube.com/watch?v%3DvQO7F2Q9DwA][Magit Introduction and Demonstration]] illustrates /rebasing/. The author recommends the following key binding

#+BEGIN_SRC emacs-lisp :eval never :tangle yes
  (global-set-key (kbd "C-x g") 'magit-status)
#+END_SRC

See also [[https://www.youtube.com/watch?v=mtliRYQd0j4&feature=youtu.be][Rewrite git history with Emacs, magit and git rebase]]. This [[https://www.reddit.com/r/emacs/comments/3w2yo8/magit_key_commands_changed/][reddit thread]] discusses the recent changes to magit.

** General configuration

Git project should not be handled by =vc=

#+BEGIN_SRC emacs-lisp
(delete 'Git vc-handled-backends)
#+END_SRC

Under windows, specify the path to =git=

#+BEGIN_SRC emacs-lisp
  (when windowsp (add-to-list 'exec-path "C:/Program Files (x86)/Git/bin/"))
#+END_SRC

** Issues under Windows

*** Staging hunks/regions
    :LOGBOOK:
    CLOCK: [2016-04-08 Fri 08:15]--[2016-04-08 Fri 08:50] =>  0:35
    CLOCK: [2016-04-07 Thu 07:30]--[2016-04-07 Thu 08:00] =>  0:30
    CLOCK: [2016-04-06 Wed 08:20]--[2016-04-06 Wed 08:45] =>  0:25
    CLOCK: [2016-04-05 Tue 07:50]--[2016-04-05 Tue 08:05] =>  0:15
    :END:

From the [[https://raw.githubusercontent.com/magit/magit/master/Documentation/RelNotes/2.6.0.txt][release notes]] of version 2.6.0

#+BEGIN_QUOTE
Staging hunks/regions belonging to files with CRLF line endings on Windows (or, to be precise, when =default-process-coding-system= had CRLF end-of-line conversion) ended up erroneously staging changes with LF line endings.  Magit now ensures line endings are preserved by enforcing a =process-coding-system= with LF end-of-line conversion.  The new behavior may be disabled by setting the option =magit-process-ensure-unix-line-ending= to =nil=.
#+END_QUOTE

However, on my windows box, this new feature seems to cause the following error message

#+BEGIN_EXAMPLE
wrong-type-argument list utf-8
#+END_EXAMPLE

I therefore disable this feature

#+BEGIN_SRC emacs-lisp
  (setq magit-process-ensure-unix-line-ending nil)
#+END_SRC

*** Pushing from Magit
    :LOGBOOK:
    CLOCK: [2016-04-21 Thu 07:10]--[2016-04-21 Thu 07:25] =>  0:15
    :END:

From the [[https://github.com/magit/magit/wiki/Pushing-with-Magit-from-Windows][official website]],

#+BEGIN_QUOTE
Windows does not have the concept of a PTY, so there is no way for Emacs to intercept password prompts from Git.
#+END_QUOTE

The solution that I adopted is to use =guit-gui--askpass=, even if it does not integrate well with emacs.

#+BEGIN_SRC emacs-lisp
  (when windowsp (setenv "GIT_ASKPASS" "git-gui--askpass"))
#+END_SRC

** FAIT Insert default commit messages
:LOGBOOK:
CLOCK: [2017-05-16 Tue 08:15]--[2017-05-16 Tue 08:45] =>  0:30
:END:

My notes are version controlled. However, I find it difficult to
enclose a meaningful commit message on each commit. So I end up using
a standard message recording the date and time. The following function
makes the whole process automatic. It is bound to =C-& C=.

#+BEGIN_SRC emacs-lisp
  (defun sb-magit-stage-and-commit-all ()
    (interactive)
    (magit-shell-command (concat "git commit -a -m \""
                                 (format-time-string "%d/%m/%Y %H:%M")
                                 "\"")))

  (define-key sb-map (kbd "C") 'sb-magit-stage-and-commit-all)
#+END_SRC

* AUCTeX and RefTeX
  :LOGBOOK:
  CLOCK: [2016-11-17 Thu 07:50]--[2016-11-17 Thu 08:00] =>  0:10
  CLOCK: [2016-06-03 Fri 08:30]--[2016-06-03 Fri 08:50] =>  0:20
  CLOCK: [2016-06-02 Thu 07:20]--[2016-06-02 Thu 09:00] =>  1:40
  CLOCK: [2016-05-25 Wed 08:10]--[2016-05-25 Wed 08:50] =>  0:40
  CLOCK: [2016-05-24 Tue 08:00]--[2016-05-24 Tue 09:30] =>  1:30
  CLOCK: [2016-05-02 Mon 08:30]--[2016-05-02 Mon 09:10] =>  0:40
  CLOCK: [2016-04-29 Fri 07:35]--[2016-04-29 Fri 07:45] =>  0:10
  :END:

#+BEGIN_SRC emacs-lisp
(require 'tex)
#+END_SRC

** Braces and such

Turn on electric mode (closing braces are automatically inserted, see [[info:auctex#Insertion of Quotes, Dollars, and Braces][Insertion of Quotes, Dollars, and Braces]] in the AUCTeX doc). Typing =C-q= before entering the opening brace deactivates this feature.

#+BEGIN_SRC emacs-lisp
(setq LaTeX-electric-left-right-brace t)
(setq TeX-electric-math (quote ("\\(" . "\\)")))
#+END_SRC

** Multi-files projects

By default, assume that the file is a master file.

#+BEGIN_SRC emacs-lisp
  (setq-default TeX-master t)
#+END_SRC

** UN_JOUR Files parsing

This section needs some love.

#+BEGIN_SRC emacs-lisp
  (setq TeX-auto-save nil)
  (setq TeX-parse-self t)
#+END_SRC

** Fontification of macros

See [[info:auctex#Fontification of macros][Fontification of macros]] in the AUCTeX doc.

#+BEGIN_SRC emacs-lisp
  (setq font-latex-match-reference-keywords '(("citeauthor" "*{")
                                              ("citetext" "{")
                                              ("citeyear" "{")
                                              ("citeyearpar" "{")
                                              ("citep" "*[{")
                                              ("citet" "*[{")
                                              ("citealt" "*[{")
                                              ("citealp" "*[{")))
#+END_SRC

** LaTeX processor

#+BEGIN_SRC emacs-lisp
  (setq LaTeX-command "latex")
  (setq-default TeX-PDF-mode t)
  (setq TeX-command "tex")
#+END_SRC

=TeX-next-error (C-c `)= sometimes fails. From the [[https://www.gnu.org/software/auctex/manual/auctex/FAQ.html][AUCTeX FAQ]]

#+BEGIN_QUOTE
When writing the log file, TeX puts information related to a file, including error
messages, between a pair of parentheses. AUCTeX determines the file where the error
happened by parsing the log file and counting the parentheses. This can fail when
there are other, unbalanced parentheses present.

As a workaround you can activate so-called file:line:error messages for the log file.
(Those are are easier to parse, but may lack some details.) Either you do this in the
configuration of your TeX system (consult its manual to see where this is) or you add
a command line switch to the (la)tex call, e.g. by customizing LaTeX-command-style or
TeX-command-list.
#+END_QUOTE

#+BEGIN_SRC emacs-lisp
(setq LaTeX-command-style '(("" "%(PDF)%(latex) -file-line-error %S%(PDFout)")))
#+END_SRC

** Support for SyncTeX

See [[info:auctex#Forward and Inverse Search][Forward and Inverse Search]] in the AUCTeX doc.

#+BEGIN_SRC emacs-lisp
  (setq TeX-source-correlate-method (quote synctex))
  (setq TeX-source-correlate-mode t)
  (setq TeX-source-correlate-start-server t)
#+END_SRC

** Viewers

We define =sb-TeX-pdf-viewer-command= which can be custom-set. This variable holds the full path to the PDF viewer, including the command line options (synctex and such). We use a custom =:set= function for the =sb-TeX-pdf-viewer-command= variable, in order to update =TeX-view-program-list=, which depends on it.

#+BEGIN_SRC emacs-lisp
  (defun sb-set-TeX-pdf-viewer-command (symbol value)
    "The function to be called when modifying `sb-TeX-pdf-viewer-command'
  when using the Customize user interface. This setter updates
  `TeX-view-program-list', taking care of duplicate entries."
    (progn (setq TeX-view-program-list
                 (cons (list "SB PDF viewer" value)
                       (cl-remove "SB PDF viewer" TeX-view-program-list
                                  :test (lambda (left right)
                                          (equal left (car right))))))
           (set-default symbol value)))

  (defcustom sb-TeX-pdf-viewer-command ""
    "Command line (including options) to be passed to `TeX-view'.
  For SumatraPDF (Windows platforms), set this variable to

      \"C:\\opt\\SumatraPDF-3.0\\SumatraPDF.exe
      -reuse-instance -forward-search %b %n %o\".

  For Skim (MacOS X platforms), set this variable to

      \"/Applications/Skim.app/Contents/SharedSupport/displayline
      -r -b %n %o %b\".
  "
    :type 'string
    :group 'sb
    :tag "TeX PDF viewer command"
    :set 'sb-set-TeX-pdf-viewer-command)

  (setq TeX-view-program-selection '((output-pdf "SB PDF viewer")))
#+END_SRC

** RefTeX
:LOGBOOK:
CLOCK: [2017-03-01 Wed 17:00]--[2017-03-01 Wed 17:10] =>  0:10
CLOCK: [2017-03-01 Wed 16:35]--[2017-03-01 Wed 16:40] =>  0:05
CLOCK: [2016-08-18 Thu 16:00]--[2016-08-18 Thu 16:30] =>  0:30
:END:

#+BEGIN_SRC emacs-lisp
  (require 'reftex)

  (add-hook 'latex-mode-hook 'turn-on-reftex)
  (add-hook 'LaTeX-mode-hook 'turn-on-reftex)

  (setq reftex-load-hook (quote (imenu-add-menubar-index)))
  (setq reftex-mode-hook (quote (imenu-add-menubar-index)))
#+END_SRC

AUCTeX/RefTeX integration

#+BEGIN_SRC emacs-lisp
  (setq reftex-plug-into-AUCTeX t)
#+END_SRC

Insert simple labels, like ‘eq:22’ or ‘sec:13’ (no query). See [[info:reftex#Options%20-%20Creating%20Labels][Creating Labels]].

#+BEGIN_SRC emacs-lisp
  (setq reftex-insert-label-flags (quote (nil nil)))
#+END_SRC

On calling =reftex-reference=, do not prompt for reference macro (=\ref=, =\pageref=, etc...).

#+BEGIN_SRC emacs-lisp
  (setq reftex-ref-macro-prompt nil)
#+END_SRC

Register axiom, theorem and remark environments so that they get properly numbered.

#+BEGIN_SRC emacs-lisp
  (setq reftex-label-alist
        '(("axiom"   ?a "ax:"  "~\\ref{%s}" nil ("axiom"   "ax.") -2)
          ("theorem" ?h "thr:" "~\\ref{%s}" nil   ("theorem" "th.") -3)
          ("remark" ?r "rem:" "~\\ref{%s}" t ("remark" "rem.") -4)))

  (add-hook 'LaTeX-mode-hook (lambda ()
                               (LaTeX-add-environments '("axiom" LaTeX-env-label)
                                                       '("theorem" LaTeX-env-label)
                                                       '("remark" LaTeX-env-label))))
#+END_SRC

** Insertion of references into a *.bib file
:LOGBOOK:
CLOCK: [2017-05-10 Wed 08:25]--[2017-05-10 Wed 08:40] =>  0:15
CLOCK: [2016-08-25 Thu 08:10]--[2016-08-25 Thu 08:35] =>  0:25
:END:

I have created a function =sb-insert-bibref= which prompts for a key,
and inserts a new BibTeX reference at point. This function is taylored
to the way I store my references.

  1. Keys are formed as follows: =AUTHYYYY=, where =AUTH= are the
     first four letters of the first author, and =YYYY= is the year of
     publication. In case of identical keys, a letter (A, B, C) is
     added to the end.
  2. Keys are capitalized.
  3. Papers are stored in =sb-path-to-bibliography/a/authYYYY/=, where
     =a= denotes the first letter of the first author, and =auth=
     denotes the first four letters of the first author. Note that =a=
     and =auth= are /not/ capitalized.
  4. Each folder =sb-path-to-bibliography/a/authYYYY/=
     contains the paper itself (generally, =authYYYY.pdf=), along with
     a =*.bib= file (=authYYYY.bib=).

With these principles, implementation of =sb-insert-bibref= is
straightforward.

#+BEGIN_SRC emacs-lisp
  (defun sb-bibref-path (key)
    "Return the path to a BibTeX file containing the specified KEY."
    (expand-file-name  (concat (s-left 1 key) "/" key "/" key ".bib")
                       sb-path-to-bibliography))

  (defun sb-insert-bibref (key)
    "Insert at point the BibTex file containing the specified KEY."
    (interactive "sBibTeX key: \n")
    (insert-file-contents (sb-bibref-path (downcase key))))
#+END_SRC

** bratex

#+BEGIN_SRC emacs-lisp
  (add-to-list 'load-path "~/.emacs.d/lisp/bratex")
  (require 'bratex)
  (add-hook 'LaTeX-mode-hook #'bratex-config)
#+END_SRC

* Development

** C

#+BEGIN_SRC emacs-lisp
  (setq-default c-basic-offset 4)
#+END_SRC

** Python
:LOGBOOK:
CLOCK: [2018-01-30 Tue 08:00]--[2018-01-30 Tue 08:45] =>  0:45
CLOCK: [2016-11-17 Thu 07:35]--[2016-11-17 Thu 07:50] =>  0:15
CLOCK: [2016-08-24 Wed 07:55]--[2016-08-24 Wed 08:25] =>  0:30
CLOCK: [2014-08-07 Thu 13:55]--[2014-08-07 Thu 15:00] =>  1:05
CLOCK: [2014-08-07 Thu 07:30]--[2014-08-07 Thu 10:00] =>  2:30
CLOCK: [2014-08-05 Tue 07:30]--[2014-08-05 Tue 10:30] =>  3:00
:END:

#+BEGIN_SRC emacs-lisp
  (setq python-shell-completion-native-enable nil
        python-shell-interpreter "jupyter"
        python-shell-interpreter-args "console --simple-prompt"
        python-shell-prompt-detect-enabled nil
        python-shell-prompt-output-regexp "Out\\[[0-9]+\\]:"
        python-shell-prompt-regexp "In \\[[0-9]+\\]: ")
#+END_SRC

I use Jorgen Schäfer's [[https://github.com/jorgenschaefer/elpy][elpy]] package.

#+BEGIN_SRC emacs-lisp
  (elpy-enable)
  (setq elpy-modules (quote (elpy-module-eldoc
                             elpy-module-flymake
                             elpy-module-sane-defaults)))
  (setq elpy-test-runner (quote elpy-test-test-discover-runner))
  (add-hook 'elpy-mode-hook 'whitespace-mode)
#+END_SRC

*** Other references

  - [[http://kitchingroup.cheme.cmu.edu/blog/2014/12/20/A-new-mode-for-Python-documentation/][A new mode for Python documentation]] : see in particular the Disqus comments.
  - [[https://bitbucket.org/jonwaltman/pydoc-info][pydoc-info]]

*** A_FAIRE Native completion problems
:LOGBOOK:
CLOCK: [2017-08-07 Mon 08:00]--[2017-08-07 Mon 08:45] =>  0:45
:END:

When running =M-x run-python", I get the following error message

#+BEGIN_EXAMPLE
Warning (python): Your ‘python-shell-interpreter’ doesn’t seem to support readline, yet ‘python-shell-completion-native’ was t and "ipython3" is not part of the ‘python-shell-completion-native-disabled-interpreters’ list. Native completions have been disabled locally.
#+END_EXAMPLE

A work around (under windows) seems to be

  1. Install =pyreadline=
  2. Set =python-shell-completion-native= to =t=
  3. Use simple prompt with Jupyter console: set =python-shell-interpreter-args= to

#+BEGIN_EXAMPLE
-i C:\\Users\\brisard\\Miniconda3\\Scripts\\jupyter-script.py console --simple-prompt
#+END_EXAMPLE

See also this [[https://github.com/jorgenschaefer/elpy/issues/887][bug report (elpy)]].

** Maxima
   :LOGBOOK:
   CLOCK: [2016-08-19 Fri 07:20]--[2016-08-19 Fri 07:35] =>  0:15
   CLOCK: [2016-05-09 Mon 08:45]--[2016-05-09 Mon 08:50] =>  0:05
   :END:

From the [[http://maxima.sourceforge.net/][official website]]

#+BEGIN_QUOTE
Maxima is a system for the manipulation of symbolic and numerical expressions, including differentiation, integration, Taylor series, Laplace transforms, ordinary differential equations, systems of linear equations, polynomials, sets, lists, vectors, matrices and tensors. Maxima yields high precision numerical results by using exact fractions, arbitrary-precision integers and variable-precision floating-point numbers. Maxima can plot functions and data in two and three dimensions.
#+END_QUOTE

The files for the maxima mode are not available on MELPA. They are packaged with the binaries, and I defined the variable =sb-path-to-maxima-mode=, where the relevant files are stored.

#+BEGIN_SRC emacs-lisp
  (defcustom sb-path-to-maxima-mode ""
    "Path to the folder hosting elisp files for maxima-mode.
  This is the path to the files: maxima.el, maxima-font-lock.el.
  "
    :type 'string :group 'sb :tag "Path to maxima-mode files")

  (add-to-list 'load-path sb-path-to-maxima-mode)
  (autoload 'maxima-mode "maxima" "Major mode for writing Maxima programs" t)
  (autoload 'maxima "maxima" "Run Maxima interactively" t)
  (setq auto-mode-alist (cons '("\\.ma[cx]" . maxima-mode)
                              auto-mode-alist))
#+END_SRC

* Ido

  - [[https://www.masteringemacs.org/article/introduction-to-ido-mode][Introduction to Ido Mode]]

** ido itself
:LOGBOOK:
CLOCK: [2016-05-09 Mon 08:50]--[2016-05-09 Mon 08:55] =>  0:05
:END:

#+BEGIN_SRC emacs-lisp :tangle no
  (ido-mode t)
  (ido-everywhere t)

  (setq ido-enable-flex-matching t)
  (setq ido-file-extensions-order (quote (".org" ".tex" ".bib" ".html" ".py")))
  (setq ido-ignore-extensions nil)
  (setq ido-ignore-files (quote ("\\`#"
                                 "\\`.#"
                                 "\\`\\.\\./"
                                 "\\`\\./"
                                 ".*~"
                                 ".*\\.aux\'"
                                 ".*\\.bbl\'"
                                 ".*\\.blg\'"
                                 ".*\\.bst\'"
                                 ".*\\.log\'"
                                 ".*\\.out\'"
                                 ".*\\.pdf\'"
                                 ".*\\.spl\'"
                                 ".*\\.synctex\\.gz\'"
                                 ".*\\.toc\'"
                                 ".*\\.o\'"
                                 ".*\\.so\'"
                                 ".*\\.a\'"
                                 ".*\\.elc\'"
                                 ".*\\.pyc\'"
                                 ".*\\.pyo\'"
                                 "\\.git/")))
#+END_SRC

Ido sometimes freezes emacs completely. It seems that caching is the culprit
(TBC). Here is how to deactivate that functionality

#+BEGIN_SRC emacs-lisp :tangle no
  (setq ido-enable-last-directory-history nil)
#+END_SRC

** ido-completing-read+
:LOGBOOK:
CLOCK: [2017-08-30 Wed 13:55]--[2017-08-30 Wed 14:05] =>  0:10
CLOCK: [2016-09-24 Sat 06:20]--[2016-09-24 Sat 06:25] =>  0:05
:END:

[[https://github.com/DarwinAwardWinner/ido-completing-read-plus][ido-completing-read+]] replaces stock emacs completion with ido
completion wherever it is possible to do so without breaking things.

#+BEGIN_SRC emacs-lisp :tangle no
  (require 'ido-completing-read+)
  (ido-ubiquitous-mode t)
#+END_SRC

* Text editing

** Trailing whitespaces
   :LOGBOOK:
   CLOCK: [2016-08-19 Fri 07:40]--[2016-08-19 Fri 07:45] =>  0:05
   :END:

In selected modes, show trailing whitespaces and empty lines at the end of the buffer. This is defined as a mode hook (which requires a function).

#+BEGIN_SRC emacs-lisp
  (add-hook 'python-mode-hook (lambda() (setq show-trailing-whitespace t)))
#+END_SRC

In all modes, empty lines at the end of the buffer are shown, and trailing white spaces are removed when buffer is saved.

#+BEGIN_SRC emacs-lisp
  (setq indicate-empty-lines nil)
  (add-hook 'before-save-hook 'delete-trailing-whitespace)
#+END_SRC

** Whitespace mode
   :LOGBOOK:
   CLOCK: [2016-08-19 Fri 07:45]--[2016-08-19 Fri 07:55] =>  0:10
   :END:

From the [[https://www.emacswiki.org/emacs/WhiteSpace][EmacsWiki]]: "This package is a minor mode to visualize blanks (TAB, (HARD) SPACE and NEWLINE)". Here are the UTF-8 values used below

|------------+-------------------------+---|
| Code point | Meaning                 |   |
|------------+-------------------------+---|
| U+0009     | TAB                     |   |
| U+000A     | LINE FEED               |   |
| U+0020     | SPACE                   |   |
| U+0024     | DOLLAR SIGN             | $ |
| U+002E     | FULL STOP               | . |
| U+003E     | GREATER THAN SIGN       | > |
| U+00B6     | PILCROW SIGN            | ¶ |
| U+00B7     | MIDDLE DOT              | · |
| U+2192     | RIGHTWARDS ARROW        | → |
| U+21E5     | RIGHTWARDS ARROW TO BAR | ⇥ |
| U+23CE     | RETURN SYMBOL           | ⏎ |
|------------+-------------------------+---|

#+BEGIN_SRC emacs-lisp
  (require 'whitespace)

  (setq whitespace-line-column 80)

  (setq whitespace-display-mappings
        '((space-mark #x0020  [#x00B7] [#x002E])
          (newline-mark #x00A [#x00B6 #x000A] [#x0024 #x000A])
          (tab-mark #x009 [#x2192 #x009] [#x003E #x009])
          ))

  (setq whitespace-style (quote (face lines-tail)))
#+END_SRC

* Easy PG (GnuPG interface for Emacs)

#+BEGIN_SRC emacs-lisp
  (require 'epa-file)
  (epa-file-enable)
#+END_SRC

* Ispell
:LOGBOOK:
CLOCK: [2016-12-06 Tue 08:25]--[2016-12-06 Tue 09:10] =>  0:45
CLOCK: [2016-12-05 Mon 08:30]--[2016-12-05 Mon 09:00] =>  0:30
:END:

The spell checker is selected through the =ispell-program-name= variable. The following code snippet sets the dictionary list for hunspell. However, on the first execution of =ispell= in an emacs session, an error is raised

#+BEGIN_EXAMPLE
split-string: Wrong type argument: stringp, nil
#+END_EXAMPLE

On trying again, ispell works like a charm.

#+BEGIN_SRC emacs-lisp
  (setq ispell-local-dictionary-alist (quote (("american"
                                               "[[:alpha:]]"
                                               "[^[:alpha:]]"
                                               "[']"
                                               t
                                               ("-d" "en_US")
                                               "~tex" undecided))))

  (setq ispell-dictionary "american")
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (setq ispell-tex-skip-alists
        (list
         (append (car ispell-tex-skip-alists)
                 '(("\\\\cite"            ispell-tex-arg-end)
                   ("\\\\nocite"          ispell-tex-arg-end)
                   ("\\\\includegraphics" ispell-tex-arg-end)
                   ("\\\\author"          ispell-tex-arg-end)
                   ("\\\\ref"             ispell-tex-arg-end)
                   ("\\\\eqref"           ispell-tex-arg-end)
                   ("\\\\label"           ispell-tex-arg-end)
                   ("\\\\cite[tp]"        ispell-tex-arg-end)
                   ))
         (cadr ispell-tex-skip-alists)))
#+END_SRC

* sb-passwd

This is a small package that I wrote in order to use management of
credentials, in particular creation/insertion of passwords.

#+BEGIN_SRC emacs-lisp
  (add-to-list 'load-path "~/.emacs.d/lisp/sb-passwd")
  (require 'sb-passwd)
  (sb-passwd-append-from-table
   (cdr (delq 'hline
              (sb-passwd-load-table-from-file
               (expand-file-name "notes/personnelles/mots_de_passe.gpg"
                                 sb-path-to-local-documents)
               "credentials"))) 0 1 2)

  (define-key sb-map (kbd "p") 'hydra-sb-passwd/body)
#+END_SRC

* Packages I should start to use

  - [[https://github.com/emacs-tw/awesome-emacs][Awesome Emacs]]
  - [[http://emacsthemes.com/][Emacs Themes]]

** Ivy, Counsel and Swiper
:LOGBOOK:
CLOCK: [2017-10-03 Tue 09:00]--[2017-10-03 Tue 09:20] =>  0:20
:END:

  - [[https://writequit.org/denver-emacs/presentations/2017-04-11-ivy.html][Ivy, Counsel and Swiper]]

#+BEGIN_SRC emacs-lisp :tangle yes
  (ivy-mode 1)
  (counsel-mode 1)
  (setq ivy-case-fold-search-default (quote always))
#+END_SRC

** eyebrowse

[[https://github.com/wasamasa/eyebrowse][eyebrowse]] is a global minor mode for Emacs that allows you to manage
your window configurations in a simple manner, just like tiling window
managers like i3wm with their workspaces do. It displays their current
state in the modeline by default. The behaviour is modeled after
ranger, a file manager written in Python.

** IMenu

See also

  - [[https://github.com/vspinu/imenu-anywhere][imenu-anywhere]]
  - [[https://www.wisdomandwonder.com/article/10358/easily-browse-imenu-entries-in-a-buffer][Easily Browse Imenu Entries In A Buffer]]
  - [[https://github.com/ancane/popup-imenu][Popup-imenu]]

** imenu-list
:LOGBOOK:
CLOCK: [2017-01-19 Thu 08:00]--[2017-01-19 Thu 08:10] =>  0:10
:END:

[[https://github.com/bmag/imenu-list][imenu-list]]

** Yasnippet

  - [[http://howardism.org/Technical/Emacs/templates-tutorial.html][Having Emacs Type for You]]
  - [[http://pragmaticemacs.com/emacs/email-templates-in-mu4e-with-yasnippet/][Email templates in mu4e with yasnippet]] (Pragmatic Emacs)
  - [[http://pragmaticemacs.com/emacs/multiple-choices-in-yasnippets/][Multiple choices in yasnippets]] (Pragmatic Emacs)

** Calfw - A calendar framework for Emacs

  - [[https://github.com/kiwanami/emacs-calfw][Calfw - A calendar framework for Emacs]]

** ggtags

  - [[https://github.com/leoliu/ggtags][Emacs frontend to GNU Global source code tagging system]]

** RSS
:LOGBOOK:
CLOCK: [2016-03-29 Tue 11:55]--[2016-03-29 Tue 13:55] =>  2:00
CLOCK: [2016-03-21 Mon 08:20]--[2016-03-21 Mon 09:00] =>  0:40
:END:

I have been exploring several options to read RSS threads from within emacs. =gnus= was the first choice. However, there are a few threads I failed to subscribe to.

I also gave up =newsticker= because

  - collection of new threads frequently fails,
  - the state (read/unread) threads is not saved frequently enough.

** Regular expressions

  - [[https://github.com/benma/visual-regexp.el][visual-regexp]] is like replace-regexp, but with live visual feedback directly in the buffer
  - [[https://github.com/mhayashi1120/Emacs-wgrep][wgrep]] allows you to edit a grep buffer and apply those changes to the file buffer

** Raibow delimiters

From the [[http://www.emacswiki.org/emacs/RainbowDelimiters][EmacsWiki]]

#+BEGIN_QUOTE
RainbowDelimiters is a “rainbow parentheses”-like mode which highlights parens, brackets, and braces according to their depth. Each successive level is highlighted a different color. This makes it easy to spot matching delimiters, orient yourself in the code, and tell which statements are at the same depth.
#+END_QUOTE

** smex

[[https://github.com/nonsequitur/smex][Smex]] is a M-x enhancement for Emacs. Built on top of Ido, it provides a convenient interface to your recently and most frequently used commands. And to all the other commands, too.

** crux

[[https://github.com/bbatsov/crux][crux]] is a Collection of Ridiculously Useful eXtensions for Emacs. crux bundles a few useful interactive commands to enhance your overall Emacs experience.

** dired-hacks

From [[https://github.com/Fuco1/dired-hacks][Github]]

#+BEGIN_QUOTE
Collection of useful dired additions. I don't want this become another dired+, so I'm splitting all the functionality into separate mutually independent packages. All shared functionality and helpers will be extracted into a single package dired-hacks-utils, so that will be the only dependence.
#+END_QUOTE

** icicles

  - [[http://www.emacswiki.org/emacs/Icicles_-_Nutshell_View][Icicles]]

** Hydra
:LOGBOOK:
CLOCK: [2016-08-18 Thu 06:30]--[2016-08-18 Thu 06:40] =>  0:10
CLOCK: [2016-06-30 Thu 07:15]--[2016-06-30 Thu 07:40] =>  0:25
CLOCK: [2016-06-30 Thu 05:45]--[2016-06-30 Thu 06:25] =>  0:40
CLOCK: [2016-06-28 Tue 08:05]--[2016-06-28 Tue 09:20] =>  1:15
:END:

From the [[https://github.com/abo-abo/hydra][repository]]

#+BEGIN_QUOTE
This is a package for GNU Emacs that can be used to tie related commands into a family of short bindings with a common prefix - a Hydra.
#+END_QUOTE

See also

  - [[http://ericjmritz.name/2015/10/14/some-personal-hydras-for-gnu-emacs/][Some Personal Hydras for GNU Emacs]]
  - [[http://oremacs.com/2016/04/04/hydra-doc-syntax/][Extended syntax for hydra docstrings]]

We first define a hydra to insert various types of arrows.

** Info mode

  - Learn about keystrokes
  - Sort manuals more conveniently

** undo-tree

  - [[https://www.emacswiki.org/emacs/UndoTree][EmacsWiki: Undo Tree]]

** expand-region

[[https://github.com/magnars/expand-region.el][expand-region]]

** wgrep

See [[http://oremacs.com/2015/01/27/my-refactoring-workflow/][this post]] on refactoring.

** zotxt

See [[https://gitlab.com/egh/zotxt][zotxt: a Zotero extension for text]]

#+BEGIN_QUOTE
zotxt is a Zotero extension for supporting utilities that deal with plain text files (e.g., markdown, reStructuredText, latex, etc.).
#+END_QUOTE

See also Michael Behr's blog post: [[http://www.mkbehr.com/posts/a-research-workflow-with-zotero-and-org-mode/][A research workflow with Zotero and Org mode]].

** rx (built-in package)

#+BEGIN_QUOTE
This is another implementation of sexp-form regular expressions.
It was unfortunately written without being aware of the Sregex
package coming with Emacs, but as things stand, Rx completely
covers all regexp features, which Sregex doesn't, doesn't suffer
from the bugs mentioned in the commentary section of Sregex, and
uses a nicer syntax (IMHO, of course :-).
#+END_QUOTE

See also

  - [[http://francismurillo.github.io/2017-03-30-Exploring-Emacs-rx-Macro/][Exploring Emacs rx Macro]]

** auth-source

  - [[https://www.masteringemacs.org/article/keeping-secrets-in-emacs-gnupg-auth-sources][Keeping Secrets in Emacs with GnuPG and Auth Sources]] (Mastering
    Emacs)

** winner-mode (built-in)

[[info:emacs#Window%20Convenience][Convenience Features for Window Handling]]

#+BEGIN_QUOTE
Winner mode is a global minor mode that records the changes in the
window configuration (i.e., how the frames are partitioned into
windows), so that you can undo them.
#+END_QUOTE

** dumb-jump

#+BEGIN_QUOTE
[[https://github.com/jacktasia/dumb-jump][dumb-jump]] is an Emacs "jump to definition" package with support for
multiple programming languages that favors "just working". This means
minimal -- and ideally zero -- configuration with absolutely no stored
indexes (TAGS) or persistent background processes. Dumb Jump requires
at least GNU Emacs 24.3.
#+END_QUOTE

** PDF tools

  - [[http://irreal.org/blog/?p=4727][PDF Tools for Emacs]] (Irreal)
  - [[https://codearsonist.com/reading-for-programmers][Reading for Programmers]]

* Blog-related customizations
  :LOGBOOK:
  CLOCK: [2016-08-23 Tue 07:35]--[2016-08-23 Tue 07:45] =>  0:10
  :END:

#+BEGIN_SRC emacs-lisp
  (sb-load-file-when-exists (expand-file-name "blog/sb-blog.el"
                                              sb-path-to-local-documents))
#+END_SRC
